"""add_markdown_content_to_file_uploads

Revision ID: 3124f6c9e3d7
Revises: 41e2959d1b66
Create Date: 2026-01-08 03:50:27.354720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3124f6c9e3d7'
down_revision: Union[str, Sequence[str], None] = '41e2959d1b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('markdown_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'markdown_content')
    # ### end Alembic commands ###
