"""add_agents_table_and_conversation_agent_id

Revision ID: 7c5da4272a92
Revises: 3124f6c9e3d7
Create Date: 2026-01-09 05:54:32.112931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c5da4272a92'
down_revision: Union[str, Sequence[str], None] = '3124f6c9e3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_index(op.f('ix_agents_uuid'), 'agents', ['uuid'], unique=True)
    op.add_column('conversations', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_column('conversations', 'agent_id')
    op.drop_index(op.f('ix_agents_uuid'), table_name='agents')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
