"""add_message_id_field

Revision ID: f54784d2e7a6
Revises: d0af3b0f6f54
Create Date: 2025-11-17 07:17:49.129618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f54784d2e7a6'
down_revision: Union[str, Sequence[str], None] = 'd0af3b0f6f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###
