"""Refactor to soft foreign keys with ORM relationships and cascade delete

Revision ID: 3c7c6ad1f994
Revises: a24f5bf86278
Create Date: 2025-11-12 09:20:48.962744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c7c6ad1f994'
down_revision: Union[str, Sequence[str], None] = 'a24f5bf86278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_conversation_uuid_fkey'), 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('messages_conversation_uuid_fkey'), 'messages', 'conversations', ['conversation_uuid'], ['uuid'])
    # ### end Alembic commands ###
