"""Restore database-level foreign key for messages.conversation_uuid

Revision ID: d0af3b0f6f54
Revises: 3c7c6ad1f994
Create Date: 2025-11-12 09:36:33.109335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0af3b0f6f54'
down_revision: Union[str, Sequence[str], None] = '3c7c6ad1f994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
